In [1]:
import os;
import sys;
import numpy as np;
import random;
# from tensorflow import keras;
import glob;
import math;
import time;

In [2]:
sys.path.append(os.getcwd());
sys.path.append(os.path.join(os.getcwd(), 'common'));

In [3]:
import common.utils as U;
import common.tlopts as tlopts
import resources.TLModels as tlmodels;

In [35]:
original_learning_dataset20 = "../../../CodeRepo/SED_Repo/ACDNet/acdnet-master/datasets/esc50/wav20.npz"
test_data16 = "./datasets/fold1_test16000.npz"
test_dataset = np.load(test_data16,allow_pickle=True)
dataset20 = np.load(original_learning_dataset20, allow_pickle=True) 

In [36]:
# print(f"type of dataset20['fold1'] is {type(dataset20['fold1'])}")
# print(f"shape of dataset20['fold1'] is {dataset20['fold1'].}")
print(test_dataset['x'])


[[[[ 0.0000000e+00]
   [ 0.0000000e+00]
   [ 0.0000000e+00]
   ...
   [ 6.1035156e-05]
   [ 0.0000000e+00]
   [-3.0517578e-05]]]


 [[[-1.5472412e-02]
   [ 9.4604492e-03]
   [ 9.6130371e-03]
   ...
   [-3.0517578e-05]
   [ 9.1552734e-05]
   [-1.2207031e-04]]]


 [[[-3.0517578e-05]
   [ 6.1035156e-05]
   [-6.1035156e-05]
   ...
   [ 0.0000000e+00]
   [-3.0517578e-05]
   [ 3.0517578e-05]]]


 ...


 [[[ 9.2468262e-03]
   [ 5.7067871e-03]
   [ 1.1688232e-02]
   ...
   [-7.6293945e-03]
   [ 3.3813477e-02]
   [ 3.9916992e-02]]]


 [[[ 1.0803223e-02]
   [-3.5400391e-03]
   [-6.9366455e-02]
   ...
   [ 1.8096924e-02]
   [ 2.0782471e-02]
   [ 1.2969971e-02]]]


 [[[ 1.9836426e-02]
   [ 2.7069092e-02]
   [ 2.6214600e-02]
   ...
   [ 0.0000000e+00]
   [ 0.0000000e+00]
   [ 0.0000000e+00]]]]


In [6]:
print(dataset20)

NpzFile '../../../CodeRepo/SED_Repo/ACDNet/acdnet-master/datasets/esc50/wav20.npz' with keys: fold1, fold2, fold3, fold4, fold5
